name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 启用 Rust 缓存
        uses: Swatinem/rust-cache@v2

      - name: 编译
        run: cargo build --release

      - name: 测试
        run: cargo test
